config/routes.rb
Rails4fun::Application.routes.draw do

  resources :bookings

  root :to => "bookings#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :bookings

  def self.default_account
    Account.first
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :account

  TAX_RATE = 0.19

  validates :amount, :numericality => true
  validates :account, :presence => true

  before_validation :do_sth

  def self.most_expensive
    Booking.all.max(&:amount)
  end

  def do_sth
    puts "Usually I would do sth here."
  end

  def calculate_tax
    self.amount * TAX_RATE
  end

  def other_bookings_in_this_account
    self.account.bookings.reject do |b|
      b == self
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_filter :find_booking, :only => [ :edit, :update, :destroy ]

  def index
    @bookings = Booking.all
  end

  def edit
  end

  def new
    @booking = Booking.new
  end

  def create
    booking = Booking.new(params[:booking])
    booking.account = Account.default_account
    booking.save!
    redirect_to bookings_path
  end

  def update
    @booking.update_attributes(params[:booking])
    redirect_to bookings_path
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  protected

  def find_booking
    @booking = Booking.find(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def wisdom
    [
      "Sehen ist verstehen!",
      "Approachen macht glücklich!",
      "Rails ist super!"
    ]
  end

  def wise_words
    wisdom[rand(3)]
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking_form.html.erb
<%= form_for @booking do |f| %>
  <%= f.text_field :description %><br/>
  <%= f.text_field :amount %>
  <%= f.submit "Save" %>
<% end %>

app/views/bookings/edit.html.erb
<h1>Booking editieren</h1>

<%= render :partial => "booking_form" %>

app/views/bookings/index.html.erb
<h1>All your bookings</h1>

<table>
  <% @bookings.each do |booking| %>
    <tr><td><%= link_to "x", booking_path(booking), :method => :delete %></td><td><%= booking.description %></td><td><%= booking.amount %></td><td><%= link_to "Editieren", edit_booking_path(booking) %></td></tr>
  <% end %>
</table>

<p>
  <%= link_to "Neues Booking", new_booking_path %>
</p>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render :partial => "booking_form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4fun</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body style="background: #CCC;">

  <%= image_tag "cloud.jpg", :width => 100, :height => 75, :style => "float: left; margin-right: 20px;" %>
  <h1>
    <%= wise_words %>
  </h1>
  <div style="background: white; width: 800px; padding: 10px; margin: auto 0; clear: both;">
    <%= yield %>
  </div>

</body>
</html>